### PR TITLE
improve user-focused punctuation in fct_vsp.xsl

### PR DESCRIPTION
**Pull request by TallTed**
* Aligns line 346 with line 339, making both statements end with dot.
* Makes lines 341 and 348 end with question mark, implying need for user action.

### CODE REVIEW

**Review by openlink — CHANGES_REQUESTED** [review]
Why are you adding question marks? The feedback isn't a question i.e., this is simply about information related to the actions being taken by the "Anytime Query" feature.

**Comment by TallTed** [comment]
@openlink -- 
```
                      The query timed out with partial result.
                      Retry with
                      <xsl:value-of select="($timeout div 1000)"/> seconds timeout
```
This dialog/alert does two things -- _informs_ that the query timed out with (partial or no) result, and _asks_ whether to retry with _n_ seconds timeout.  The latter requires an answer from the user, by either _clicking_ or _ignoring_ the "retry" button, and is appropriately punctuated with a `?`.

**Review by kidehen — COMMENTED** [review]
Look at [this page](http://kingsley.idehen.net/fct/facet.vsp?qxml=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%20%3F%3E%3Cquery%20inference%3D%22%22%20invfp%3D%22IFP_OFF%22%20same-as%3D%22SAME_AS_OFF%22%20view3%3D%22%22%20s-term%3D%22e%22%20c-term%3D%22type%22%20agg%3D%22%22%20limit%3D%2250%22%3E%3Ctext%3EVirtuoso%3C%2Ftext%3E%3Cproperty%20iri%3D%22http%3A%2F%2Frdfs.org%2Fsioc%2Fns%23container_of%22%3E%3Cview%20type%3D%22list%22%20limit%3D%2250%22%20offset%3D%2250%22%20%2F%3E%3C%2Fproperty%3E%3C%2Fquery%3E). If a question mark is to be applied, it would be to the button label i.e., "Retry?" which indicates the existence of a choice. 

The current text you are trying to change is now actually obsolete.

**Comment by TallTed** [comment]
@kidehen /cc @danielhmills 

I see...  I thought those sentences would appear in the main UI, but I now see they're in a mouseover display tied to the "Retry" button.  Looking at [this page](http://kingsley.idehen.net/fct/facet.vsp?qxml=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%20%3F%3E%3Cquery%20inference%3D%22%22%20invfp%3D%22IFP_OFF%22%20same-as%3D%22SAME_AS_OFF%22%20view3%3D%22%22%20s-term%3D%22e%22%20c-term%3D%22type%22%20agg%3D%22%22%20limit%3D%2250%22%3E%3Ctext%3EVirtuoso%3C%2Ftext%3E%3Cproperty%20iri%3D%22http%3A%2F%2Frdfs.org%2Fsioc%2Fns%23container_of%22%3E%3Cview%20type%3D%22list%22%20limit%3D%2250%22%20offset%3D%2250%22%20%2F%3E%3C%2Fproperty%3E%3C%2Fquery%3E)...

* I think the "timeout" and "partial/no results!" info should be much more obvious, perhaps atop the table, maybe as a watermark across the table, and _definitely_ not requiring a mouseover of "Retry" to be revealed.

* I think the "Retry" button should be styled as a button.  Right now, it looks like advisory text.

* The invisible scroll-bar on the right is not obviously present.  (I'm used to such things, and it still took me more than a few ticks to comprehend it.)  The slider looks like a decoration, not an interactive element.

* The **`Go to: ___ Show` 50 `51 - 100 of 1494 total  <  >`** is challenging. I think something like 
  ```
  Show ___ rows, from ___ to ### of ### total  <  >
  ```
  where both `___` and `###` are filled in by FCT when delivering a page (including the default row-count and `0` for the others when results are empty), `___` are user editable, and `###` are not editable.

* I have a giant screen.  It's generally worthwhile to limit the width of textual content, because of the way eyes work, but there's no reason not to use the full height of my screen.

* Given that the active real estate is *part* of my open window, the odd clickable box at far-upper-right of my window should actually be at far-right of the active real estate; similarly, the mysterious box it opens should be at far-left of active real estate, not at far-left of my window.

* I suggest changing the About... box title from `About This Virtuoso Faceted Browser Instance` to `About this Virtuoso Faceted Browser instance`.

**Comment by TallTed** [comment]
@kidehen @danielhmills @openlink 

Conflicts resolved.  Please review and merge.

**Pull request closed without merging**
